services:
  app:
    container_name: flexiblelog-app
    build: .
    env_file:
      - .env.local
    environment:
      NODE_ENV: production
    expose:
      - "3000"

  nginx:
    container_name: flexiblelog-proxy
    image: nginx:alpine
    ports:
      - "3000:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.certs:/etc/nginx/certs:ro
    depends_on:
      - app
